<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="GL-2.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [2]:
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
new=np.array(list_temperature)
new

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [25]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
w1=np.array(weights)
w1[w1>68]




array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [38]:
np.random.seed(23)
n1=np.random.randint(low=20,high=40,size=(1,10))
n1

array([[39, 26, 28, 29, 28, 33, 32, 27, 39, 26]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [46]:
n1=np.arange(1,6)
n2=np.array(n1)
n2
np.power(n2,5)

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [24]:
n1=np.arange(50,101)
n1
n1[n1%2!=0]

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [44]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
A1=np.array(A)
A1.sum(axis=0)

array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [100]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
n1=np.array(num)
np.remainder(n1,8)


array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [118]:
A1=np.arange(1,21)
A2=np.arange(1,21).reshape(4,5)
A2
A2[1]


array([ 6,  7,  8,  9, 10])

In [124]:
A1=np.arange(1,21)
A2=np.arange(1,21).reshape(2,10)
A2
A2[1][0:6]



array([11, 12, 13, 14, 15, 16])

## <table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [89]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]
n1=np.array(prices_monday)
n2=np.array(prices_tuesday)
print(np.intersect1d(n1,n2))
print(np.union1d(n1,n2))
print(np.setdiff1d(n1,n2))



[10 50]
[ 10  20  30  50  60  70  80  90 125]
[30 60 90]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [53]:
weights = [57, 69, 54, 65 ,71, 62, 56]
w1=np.array(weights)
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
h1=np.array(heights)
bmi=w1/(h1**2)
print(bmi)

[22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [58]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
a2=[[5,7]]
np.insert(array1,3,a2,axis=1)

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [61]:
n1=np.eye(5)
n1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [64]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
M1=np.transpose(M)
M1

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

In [125]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
M1=np.array(M)
M1.T


array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [69]:
A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]
A3=np.vstack(tup=(A1,A2))

print(A3)


[[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]
[[ 5  9  8 -7]
 [ 7  6  0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [70]:
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]
A4=np.hstack(tup=(A1,A2))
print(A4)

[[-81  75  40  15  54]
 [ 27  67  52  39  56]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [126]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
A1=np.array(A)
np.vsplit(A1,3)

[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

### <table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [86]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
B1=np.array(B)
np.hsplit(B1,2)

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [108]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]
for i ,j in zip(L1,L2):
    c=i+j
    print(c)

66
119
120
81
103
136
82


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [99]:
numbers = [6, 5, 3, 15]
n1=np.array(numbers)
n1
for n in n1:
    c=(2*n-1)/(n+5)
    print(c)
    
   

1.0
0.9
0.625
1.45
